#!/bin/bash
# muslx32toolkit - scripts to generate a stage3 and stage4 image for Gentoo Linux using crossdev for the muslx32 profile
# Copyright (C) 2017  Orson Teodoro <orsonteodoro@yahoo.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#note: this script is simplifies compiling kernel.  see gkern-config to set it up before using it.

source /etc/portage/make.conf
source /usr/src/gkern-config

mount /dev/${BOOT_PARTITION} /boot
cd /boot

genkernel --kernel-cc=${CHOST}-gcc --utils-cc=${CHOST}-gcc --kernel-config=/etc/kernels/kernel-config-x86_64-$VER-gentoo$REV --kernel-ld=/usr/${CHOST}/binutils-bin/$(ld -v | cut -d' ' -f 4)/ld.bfd --menuconfig all
#mount windows partition first so grub can detect it
if [ -e /usr/bin/ntfs-3g ] ; then
	mkdir -p /mnt/windows
	ntfs-3g /dev/${WINDOWS_PARTITION} /mnt/windows
fi
#grub-mkconfig -o /boot/grub/grub.cfg #uncomment to generate a grub.cfg automatically
grub-install /dev/${BOOT_DRIVE}

#emerge additional modules below
#emerge -1 <yourmodulehere>
