#!/bin/bash
# muslx32toolkit - scripts to generate a stage3 and stage4 image for Gentoo Linux using crossdev for the muslx32 profile
# Copyright (C) 2017  Orson Teodoro <orsonteodoro@yahoo.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#note: this contains the settings for the create-stage3 and create-stage4 scripts

PORTAGE_SNAPSHOT_TARBALL="portage-latest.tar.xz"
STAGE3_TARBALL="stage3-x32-20170316.tar.bz2"

___CHOST___="x86_64-pc-linux-muslx32"
___CBUILD___="x86_64-pc-linux-gnux32"
___ARCH___="amd64"
___LIBC___="musl"

GCC_VERSION="5.4.0-r3"
MUSL_VERSION="1.1.16"
PROFILE_VERSION="13.0"
CROSSDEV_TARGET="${___CHOST___}"
OPENSSL_VERSION="1.0.2k"
ZLIB_VERSION="1.2.11"
NET_TOOLS_VERSION="1.60_p20161110235919"
AUTOMAKE_VERSION_SLOT="1.14"
FIREFOX_VERSION="45.4.0"
GUILE_VERSION="2.0.14"
SPIDERMONKEY_VERSION="1.8.5-r5"

MY_CFLAGS='-O2 -pipe -fomit-frame-pointer'

LLVM_VERSION="3.8.1-r2" #3.9.1 and above is broken
PYTHON_2_VERSION="2.7"
PYTHON_3_VERSION="3.4"
