#!/bin/bash
# muslx32toolkit - scripts to generate a stage3 and stage4 image for Gentoo Linux using crossdev for the muslx32 profile
# Copyright (C) 2017  Orson Teodoro <orsonteodoro@yahoo.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#note: this script is used to populate proc and dev in cases like rebooting

pushd `dirname $0` > /dev/null
MUSLX32_TOOLKIT_FOLDER=`pwd -P`
popd > /dev/null

source ${MUSLX32_TOOLKIT_FOLDER}/config

CROSSDEV_ROOT="$1"

if [[ -z "${CROSSDEV_ROOT}" ]] ; then
	echo "You need to specify the CROSSDEV_ROOT parameter for the call this script."
	echo ""
	echo $(basename "$0")" CROSSDEV_ROOT"
	echo "CROSSDEV_ROOT - where to mount the crossdev root folders.  It should contain both ${STAGE3_TARBALL} and ${PORTAGE_SNAPSHOT_TARBALL} tarballs."
	echo ""
	echo "See the contents of the script for details."
	exit 1
fi

cd "${CROSSDEV_ROOT}"
echo "CROSSDEV_ROOT is ${CROSSDEV_ROOT}"

mount --bind /dev dev
mount -t proc proc proc

cd usr/${CROSSDEV_TARGET}
mount --bind /dev dev
mount -t proc proc proc

